project_id = "gxtsgkflrgmytzrvypad"

[functions.healthcare-chat]
enabled = true
verify_jwt = false

[functions.google-fit-auth]
enabled = true
verify_jwt = false

[functions.google-fit-data]
enabled = true
verify_jwt = false

[functions.register-doctor]
enabled = true
verify_jwt = false